# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-aws-rest-api-architecture"
    dynamodb_table = "terraform-app-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-3"
  }
}