# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "moveo-hls-green-s3"
    dynamodb_table = "terraform-app-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-2"
  }
}
