name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.2.7
      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.9.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: v0.16.0
  validate:
    name: Validate modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders:
          [
            "acm",
            "authentication/cognito",
            "backend",
            "backend/elastic-beanstalk",
            "backend/api-gateway",
            "cicd",
            "cicd/cloudfront-auto-invalidator",
            "cicd/codebuild",
            "cicd/codepipeline",
            "client/amplify",
            "client/cloudfront",
            "context",
            "database",
            "database/vpc-endpoint",
            "database/db-user",
            "database/atlas-project",
            "database/atlas-cluster",
            "database/security-groups",
            "kms",
            "network/security-group",
            "network/vpc-endpoints",
            "network/vpc-flow-logs-s3-bucket",
            "network/vpc-private",
            "network/vpc-private-public",
            rds,
            waf,
          ]
    defaults:
      run:
        shell: bash
        working-directory: modules
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check modules
        run: |
          echo "Validating ${{ matrix.folders }}"...
          cd ${{ matrix.folders }} && terraform init && terraform validate && cd -
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./modules
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          # log_level: DEBUG # optional: set log level. Default WARNING
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: 
            "modules/acm,
            modules/authentication/cognito,
            modules/backend,
            modules/backend/elastic-beanstalk,
            modules/backend/api-gateway,
            modules/cicd,
            modules/cicd/cloudfront-auto-invalidator,
            modules/cicd/codebuild,
            modules/cicd/codepipeline,
            modules/client/amplify,
            modules/client/cloudfront,
            modules/context,
            modules/database,
            modules/database/vpc-endpoint,
            modules/database/db-user,
            modules/database/atlas-project,
            modules/database/atlas-cluster,
            modules/database/security-groups,
            modules/kms,
            modules/network/security-group,
            modules/network/vpc-endpoints,
            modules/network/vpc-flow-logs-s3-bucket,
            modules/network/vpc-private,
            modules/network/vpc-private-public,
            modules/rds,
            modules/waf"
          output-file: README.md
          output-method: inject
          git-push: "true"

      - name: Render terraform example complete docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./examples/${{ matrix.folders }}
          output-file: README.md
          output-method: inject
          git-push: "true"
  automerge:
    needs:
      [
        pre-commit-checks,
        validate,
        checkov-job,
        docs
      ]
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
